In [1]:
import numpy as np


In [10]:
my_list=[1,2,3]

In [11]:
arr=np.array(my_list)

In [12]:
arr

array([1, 2, 3])

In [13]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [15]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [27]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.81781084, 0.56500829, 0.38882711, 0.48348426, 0.23889751])

In [30]:
np.random.rand(5,5)

array([[0.99708042, 0.31540063, 0.23224027, 0.07489102, 0.98702303],
       [0.10730076, 0.67189757, 0.92839607, 0.55540288, 0.4074303 ],
       [0.41895972, 0.06402901, 0.91407164, 0.99151406, 0.45696171],
       [0.45264146, 0.39112312, 0.25623106, 0.96537202, 0.86064988],
       [0.87881162, 0.86321482, 0.87864778, 0.46980757, 0.38120701]])

In [31]:
np.random.randn(2)

array([0.66900781, 0.47602365])

In [32]:
np.random.randn(4,4)

array([[-0.99148865,  0.76695991, -0.08070492,  0.09989139],
       [-1.55372974, -0.07042572,  1.84758009,  0.0458495 ],
       [ 0.51712551, -1.23639466, -0.78718916,  0.34575033],
       [ 0.87131667,  0.51171805, -0.46039191, -0.96378487]])

In [33]:
np.random.randint(1,100)

86

In [34]:
np.random.randint(1,100,10)

array([27, 63, 57, 17, 75, 10, 44, 16, 97, 61])

In [35]:
arr=np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr=np.random.randint(0,50,10)

In [38]:
ranarr

array([34, 16, 19, 49, 31, 30, 41, 18, 13,  6])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr

array([34, 16, 19, 49, 31, 30, 41, 18, 13,  6])

In [41]:
ranarr.max()

49

In [43]:
ranarr.min()

6

In [44]:
ranarr

array([34, 16, 19, 49, 31, 30, 41, 18, 13,  6])

In [45]:
ranarr.argmax()

3

In [46]:
ranarr.argmin()

9

In [47]:
arr.shape

(25,)

In [49]:
arr=arr.reshape(5,5)

In [50]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.shape

(5, 5)

In [52]:
arr.dtype

dtype('int32')

In [53]:
from numpy.random import randint

In [54]:
randint(2,10)

6